name: RvLProMaster-Workspaces

on: 
    workflow_dispatch:
        inputs:
            RECOVERY_SELECT:
                description: 'Pick Your Recovery'
                required: true
                default: ''
                type: choice
                options:
                    - TWRP (twrp-12.1)
                    - PBRP (android-12.1)
                    - SHRP (shrp-12.1)
                
            URL_DEVICE_TREE: # Input Device Tree URL
                description: 'Paste Your Recovery Device Tree'
                required: true

            DEVICE_TREE_BRANCH: # Input Device Tree Branch
                description: 'Paste Your Recovery Device Tree Branch'
                required: true

            CODENAME: # Input Codename
                description: 'Input Your Codename'
                required: true

            BUILD_VARIANT: # Build Variant (bootimage, recovery, pbrp, vendor_boot)
                description: 'Select Your Variant Build'
                required: true
                type: choice
                options: 
                    - bootimage
                    - recovery
                    - vendor_boot
                    - pbrp
            
            BRAND: 
                description: 'Select Your Brand'
                required: true
                type: choice
                default: xiaomi
                options: 
                    - xiaomi

jobs: 
    build:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        env:
            packages: bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev repo jq python3 pip
            PBRP_URL: https://github.com/PitchBlackRecoveryProject/manifest_pb
            PBRP_BRANCH: android-12.1
            TWRP_URL: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp
            TWRP_BRANCH: twrp-12.1
            SHRP_URL: https://github.com/SHRP/manifest
            SHRP_BRANCH: shrp-12.1
        steps:
            - name: Check Out # Check Out
              uses: actions/checkout@v3

            - name: Cleanup Disk # Cleanup Disk
              uses: rokibhasansagar/slimhub_actions@main
            
            - name: Packages Manager
              run: |
                sudo apt-get update
                sudo apt-get upgrade
                sudo apt-get install ${{ env.packages }} -y 

            - name: Setup Workdir
              run: |
                mkdir workdir
                cd workdir/

            - name: Sync Source
              run: |
                if [ "${{ github.event.inputs.RECOVERY_SELECT }}" == "TWRP (twrp-12.1)" ]; then
                    repo init --depth=1 -u ${{ env.TWRP_URL }} -b ${{ env.TWRP_BRANCH }}
                elif [ "${{ github.event.inputs.RECOVERY_SELECT }}" == "PBRP (android-12.1)" ]; then
                    repo init --depth=1 -u ${{ env.PBRP_URL }} -b ${{ env.PBRP_BRANCH }}
                elif [ "${{ github.event.inputs.RECOVERY_SELECT }}" == "SHRP (shrp-12.1)" ]; then
                    repo init --depth=1 -u ${{ env.SHRP_URL }} -b ${{ env.SHRP_BRANCH}}
                fi
                
                repo sync --no-clone-bundle --force-sync -j$(nproc --all)

            - name: Clone Device Tree
              run: git clone ${{ github.event.inputs.URL_DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} device/${{ github.event.inputs.BRAND }}/${{ github.event.inputs.CODENAME}}

            - name: Build Progress
              run: |
                source build/envsetup.sh
                if [ "${{ github.event.inputs.RECOVERY_SELECT }}" == "TWRP (twrp-12.1)" ]; then
                    lunch twrp_${{ github.event.inputs.CODENAME }}-eng
                    mka ${{ github.event.inputs.BUILD_VARIANT }}
                elif [ "${{ github.event.inputs.RECOVERY_SELECT }}" == "PBRP (android-12.1)" ]; then
                    lunch pb_${{ github.event.inputs.CODENAME }}-eng
                    mka ${{ github.event.inputs.BUILD_VARIANT }}
                elif [ "${{ github.event.inputs.RECOVERY_SELECT }}" == "SHRP (shrp-12.1)" ]; then
                    lunch twrp_${{ github.event.inputs.CODENAME }}-eng
                    mka ${{ github.event.inputs.BUILD_VARIANT }}
                fi
